name: build-flow

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
      NX_CLOUD_ID: 6772a5535ad9512e8f5c7e0e
      NX_BRANCH: ${{ github.event.number || github.ref_name }}
      NX_CLOUD_DISTRIBUTED_EXECUTION: 'true'
      NX_BASE: ${{ github.event.pull_request.base.sha || github.event.before }}
      NX_HEAD: ${{ github.event.pull_request.head.sha || github.sha }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
      - name: Start Nx Cloud CI Run
        run: pnpm dlx nx-cloud start-ci-run"
        env:  
          NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
          NX_CLOUD_ID: 6772a5535ad9512e8f5c7e0e

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install --no-frozen-lockfile
      - uses: nrwl/nx-set-shas@v4

      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      # - run: pnpm exec nx-cloud record -- echo Hello World
      # Nx Affected runs only tasks affected by the changes in this PR/commit. Learn more: https://nx.dev/ci/features/affected
      - name: Run affected targets
        run: |
          if ! pnpm exec nx reset; then
            echo "Failed to reset Nx cache"
            exit 1
          fi
          
          if ! pnpm exec nx affected --base=$NX_BASE --head=$NX_HEAD -t lint test build --parallel=3; then
            echo "One or more tasks failed - check the logs above"
            exit 1
          fi
        env:
          NX_CLOUD_DISTRIBUTED_EXECUTION: 'true'
          NX_CLOUD_DISTRIBUTED_EXECUTION_AGENT_COUNT: 3
          NX_SKIP_NX_CACHE: 'true'
