{
  "$schema": "./node_modules/nx/schemas/nx-schema.json",
  "defaultBase": "main",
  "nxCloudId": "${process.env.NX_CLOUD_ID}",
  "targetDefaults": {
    "@nx/vite:test": {
      "cache": true,
      "inputs": [
        "default",
        "^default"
      ]
    },
    "@nx/eslint:lint": {
      "cache": true,
      "inputs": [
        "default",
        "{workspaceRoot}/.eslintrc.json",
        "{workspaceRoot}/.eslintignore",
        "{workspaceRoot}/eslint.config.js"
      ]
    },
    "build": {
      "cache": true,
      "dependsOn": ["^build"],
      "inputs": [
        "production",
        "^production"
      ]
    }
  },
  "namedInputs": {
    "sharedGlobals": [
      "{workspaceRoot}/.github/workflows/build-flow.yml"
    ],
    "default": [
      "sharedGlobals"
    ],
    "production": [
      "default",
      "!{projectRoot}/**/?(*.)+(spec|test).[jt]s?(x)?(.snap)",
      "!{projectRoot}/tsconfig.spec.json",
      "!{projectRoot}/.eslintrc.json"
    ]
  }
}
